version: "3.3"
services:
    synapse:
        image: "matrixdotorg/synapse:latest"
        restart: unless-stopped
        container_name: "synapse"
        volumes:
            - "./data:/data:Z"
        environment:
            VIRTUAL_HOST: "chat.outernet"
            VIRTUAL_PORT: 8008
            SYNAPSE_SERVER_NAME: "chat.outernet"
            SYNAPSE_REPORT_STATS: "yes"
            TZ: "America/New_York" # cabot is EST
        ports:
            - "8008:8008/tcp"
            - "8448:8448/tcp"
    cinny:
        image: "outerlan/cinny:latest" # https://github.com/aboutdavid/cinny-outerlan.git
        restart: unless-stopped
        container_name: "cinny"
        ports:
            - "8009:80/tcp"