version: "3.3"
services:
    synapse:
        image: "matrixdotorg/synapse:latest"
        restart: unless-stopped
        container_name: "synapse"
        volumes:
            - "./data:/data:Z"
        environment:
            VIRTUAL_HOST: "chat.outernet"
            VIRTUAL_PORT: 8008
            SYNAPSE_SERVER_NAME: "chat.outernet"
            SYNAPSE_REPORT_STATS: "yes"
            TZ: "America/New_York" # cabot is EST
        expose:
            - 8008
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.identity.rule=Host(`synapse.outernet`)"
            - "traefik.http.routers.identity.entrypoints=websecure"
            - "traefik.http.services.identity.loadbalancer.server.port=8008"
            - "traefik.http.services.identity.loadbalancer.server.scheme=https"
    cinny:
        image: "outerlan/cinny:latest" # https://github.com/aboutdavid/cinny-outerlan.git
        restart: unless-stopped
        container_name: "cinny"
        expose:
            - 8009:80
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.identity.rule=Host(`chat.outernet`)"
            - "traefik.http.routers.identity.entrypoints=websecure"
            - "traefik.http.services.identity.loadbalancer.server.port=8009"
            - "traefik.http.services.identity.loadbalancer.server.scheme=https"
    slackbridge:
        image: "matrixdotorg/matrix-appservice-slack:latest"
        restart: unless-stopped
        container_name: "slackbridge"
        volumes:
            - "./sb_config:/config"
        ports:
            - "5858:5858/tcp"
            - "9898:9898/tcp"
    sbpostgres:
        image: outerlan/sbpostgres:latest
        restart: unless-stopped
        container_name: "sbpostgres"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - sbpostgres:/var/lib/postgresql/data
    synapse-admin:
        container_name: synapse-admin
        hostname: synapse-admin
        build:
          context: https://github.com/Awesome-Technologies/synapse-admin.git
          args:
            - REACT_APP_SERVER=http://host.docker.internal:8008
        expose:
            - 8087
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.identity.rule=Host(`admin.chat.outernet`)"
            - "traefik.http.routers.identity.entrypoints=websecure"
            - "traefik.http.services.identity.loadbalancer.server.port=8087"
            - "traefik.http.services.identity.loadbalancer.server.scheme=https"
        restart: unless-stopped

volumes:
  sbpostgres:

networks:
  default:
    name: internal
    external: true